In [2]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

# Part A : Setup + Baseline

## Load the dataset and define:
 - X = feature matrix (numeric features only; encode categories if needed)
 - y = target

In [40]:
data = pd.read_csv("data/processed/Airbnb_Open_Data_Cleaned.csv", low_memory=False)

display(data)
# cleaning the dataset, dropping null an unnecessary values

data = data.drop(["license","country", "country_code","house_rules","name", "host_name","neighbourhood","neighbourhood_group", "last_review","service_fee"], axis=1)
valid_min_nights = data["minimum_nights"] >=1
valid_avail_365 = data["availability_365"].between(0,365)

data["minimum_nights"] =  data["minimum_nights"] >= 1
data["availability_365"] = (data["availability_365"] > 0) & (data["availability_365"] <=365)


data = data.dropna()
data.info()
data.isna().sum()
display(data)


output_path = Path("data/processed/Airbnb_Open_Data_dropped_uneccesarry_columns.csv")
data.to_csv(output_path, index=False)

SyntaxError: invalid syntax (2086300227.py, line 9)

In [38]:
# Sorting categorical columns
categorical_columns = data.select_dtypes(include=["object", "category"]).columns.tolist()

data[categorical_columns].nunique()

data_categorical = data[categorical_columns]

data

/tmp/ipykernel_6167/3261765296.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = data.select_dtypes(include=["object", "category"]).columns.tolist()

,id,host_id,host_identity_verified,lat,long,instant_bookable,cancellation_policy,room_type,construction_year,price,minimum_nights,number_of_reviews,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365
0,1001254,80014485718,unconfirmed,40.64749,-73.97237,False,strict,Private room,2020.0,966.0,True,9.0,0.21,4.0,6.0,True
1,1002102,52335172823,verified,40.75362,-73.98377,False,moderate,Entire home/apt,2007.0,142.0,True,45.0,0.38,4.0,2.0,True
3,1002755,85098326012,unconfirmed,40.68514,-73.95976,True,moderate,Entire home/apt,2005.0,368.0,True,270.0,4.64,4.0,1.0,True
4,1003689,92037596077,verified,40.79851,-73.94399,False,moderate,Entire home/apt,2009.0,204.0,True,9.0,0.10,3.0,1.0,True
5,1004098,45498551794,verified,40.74767,-73.97500,True,flexible,Entire home/apt,2013.0,577.0,True,74.0,0.59,3.0,1.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102588,6089124,85557432222,unconfirmed,40.74068,-73.98999,True,flexible,Entire home/apt,2016.0,618.0,True,177.0,3.78,4.0,1.0,False
102591,6090781,50908010324,verified,40.77408,-73.98181,False,strict,Entire home/apt,2005.0,1139.0,True,17.0,0.35,5.0,1.0,True
102593,6091885,33188605074,verified,40.72826,-73.98422,True,strict,Private room,2017.0,1099.0,True,8.0,0.16,4.0,2.0,True
102595,6092990,77864383453,unconfirmed,40.80460,-73.96545,True,moderate,Private room,2016.0,837.0,True,1.0,0.02,2.0,2.0,False
102597,6094094,11160591270,unconfirmed,40.74989,-73.93777,True,strict,Entire home/apt,2015.0,546.0,True,5.0,0.10,3.0,1.0,False

In [27]:
#Encoding categories
data = data.join(pd.get_dummies(data_categorical)).drop(categorical_columns,axis=1)
display(data)



X = data.drop(["price"], axis=1)
y = data["price"]

,id,host_id,lat,long,construction_year,price,minimum_nights,number_of_reviews,reviews_per_month,review_rate_number,...,host_identity_verified_verified,instant_bookable_False,instant_bookable_True,cancellation_policy_flexible,cancellation_policy_moderate,cancellation_policy_strict,room_type_Entire home/apt,room_type_Hotel room,room_type_Private room,room_type_Shared room
0,1001254,80014485718,40.64749,-73.97237,2020.0,966.0,True,9.0,0.21,4.0,...,False,True,False,False,False,True,False,False,True,False
1,1002102,52335172823,40.75362,-73.98377,2007.0,142.0,True,45.0,0.38,4.0,...,True,True,False,False,True,False,True,False,False,False
3,1002755,85098326012,40.68514,-73.95976,2005.0,368.0,True,270.0,4.64,4.0,...,False,False,True,False,True,False,True,False,False,False
4,1003689,92037596077,40.79851,-73.94399,2009.0,204.0,True,9.0,0.10,3.0,...,True,True,False,False,True,False,True,False,False,False
5,1004098,45498551794,40.74767,-73.97500,2013.0,577.0,True,74.0,0.59,3.0,...,True,False,True,True,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102588,6089124,85557432222,40.74068,-73.98999,2016.0,618.0,True,177.0,3.78,4.0,...,False,False,True,True,False,False,True,False,False,False
102591,6090781,50908010324,40.77408,-73.98181,2005.0,1139.0,True,17.0,0.35,5.0,...,True,True,False,False,False,True,True,False,False,False
102593,6091885,33188605074,40.72826,-73.98422,2017.0,1099.0,True,8.0,0.16,4.0,...,True,False,True,False,False,True,False,False,True,False
102595,6092990,77864383453,40.80460,-73.96545,2016.0,837.0,True,1.0,0.02,2.0,...,False,False,True,False,True,False,False,False,True,False
102597,6094094,11160591270,40.74989,-73.93777,2015.0,546.0,True,5.0,0.10,3.0,...,False,False,True,False,False,True,True,False,False,False

In [39]:
plt.figure(figsize=(25,8))
sns.heatmap(data.corr(),annot=True, cmap="YlGnBu" )

ValueError: could not convert string to float: 'unconfirmed'

## 2. Create a baseline model using all features.
    - Classification: Logistic Regression
    - Regression: Linear Regression