# WEEK 5 DATA SCIENCE ASSIGNMENT

# DBSCAN + Hierarchical Clustering

In [28]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [29]:
data = pd.read_csv("data/processed/Airbnb_Open_Data_added_features.csv")
data

,lat,long,construction_year,price,minimum_nights,number_of_reviews,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365,...,instant_bookable_True,instant_bookable_unknown,cancellation_policy_flexible,cancellation_policy_moderate,cancellation_policy_strict,cancellation_policy_unknown,room_type_Entire home/apt,room_type_Hotel room,room_type_Private room,room_type_Shared room
0,40.64749,-73.97237,2020.0,966.0,3.302585,2.302585,0.190620,4.0,2.791759,286.0,...,False,False,False,False,True,False,False,False,True,False
1,40.75362,-73.98377,2007.0,142.0,4.401197,3.828641,0.322083,4.0,1.693147,228.0,...,False,False,False,True,False,False,True,False,False,False
2,40.80902,-73.94190,2005.0,620.0,2.098612,0.000000,0.000000,5.0,1.000000,352.0,...,True,False,True,False,False,False,False,False,True,False
3,40.68514,-73.95976,2005.0,368.0,4.401197,5.602119,1.729884,4.0,1.000000,322.0,...,True,False,False,True,False,False,True,False,False,False
4,40.79851,-73.94399,2009.0,204.0,3.302585,2.302585,0.095310,3.0,1.000000,289.0,...,False,False,False,True,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102347,40.70862,-73.94651,2003.0,844.0,1.000000,0.000000,0.000000,3.0,1.000000,227.0,...,False,False,True,False,False,False,False,False,True,False
102348,40.80460,-73.96545,2016.0,837.0,1.000000,0.693147,0.019803,2.0,1.693147,NaN,...,True,False,False,True,False,False,False,False,True,False
102349,40.67505,-73.98045,2009.0,988.0,2.098612,0.000000,0.000000,5.0,1.000000,342.0,...,True,False,False,True,False,False,False,False,True,False
102350,40.74989,-73.93777,2015.0,546.0,1.693147,1.791759,0.095310,3.0,1.000000,NaN,...,True,False,False,False,True,False,True,False,False,False
102351,40.76807,-73.98342,2010.0,1032.0,1.000000,0.000000,0.000000,3.0,1.000000,69.0,...,False,False,True,False,False,False,True,False,False,False

In [30]:
data = data.dropna()
data.isna().sum()

lat                                   0
long                                  0
construction_year                     0
price                                 0
minimum_nights                        0
number_of_reviews                     0
reviews_per_month                     0
review_rate_number                    0
calculated_host_listings_count        0
availability_365                      0
host_identity_verified_unconfirmed    0
host_identity_verified_unknown        0
host_identity_verified_verified       0
instant_bookable_True                 0
instant_bookable_unknown              0
cancellation_policy_flexible          0
cancellation_policy_moderate          0
cancellation_policy_strict            0
cancellation_policy_unknown           0
room_type_Entire home/apt             0
room_type_Hotel room                  0
room_type_Private room                0
room_type_Shared room                 0
dtype: int64

In [43]:
X= data.drop(["price"], axis=1)
X

,lat,long,construction_year,minimum_nights,number_of_reviews,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365,host_identity_verified_unconfirmed,...,instant_bookable_unknown,cancellation_policy_flexible,cancellation_policy_moderate,cancellation_policy_strict,cancellation_policy_unknown,room_type_Entire home/apt,room_type_Hotel room,room_type_Private room,room_type_Shared room,cluster
0,40.64749,-73.97237,2020.0,3.302585,2.302585,0.190620,4.0,2.791759,286.0,True,...,False,False,False,True,False,False,False,True,False,-1
1,40.75362,-73.98377,2007.0,4.401197,3.828641,0.322083,4.0,1.693147,228.0,False,...,False,False,True,False,False,True,False,False,False,-1
2,40.80902,-73.94190,2005.0,2.098612,0.000000,0.000000,5.0,1.000000,352.0,False,...,False,True,False,False,False,False,False,True,False,-1
3,40.68514,-73.95976,2005.0,4.401197,5.602119,1.729884,4.0,1.000000,322.0,True,...,False,False,True,False,False,True,False,False,False,-1
4,40.79851,-73.94399,2009.0,3.302585,2.302585,0.095310,3.0,1.000000,289.0,False,...,False,False,True,False,False,True,False,False,False,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102345,40.71845,-74.01183,2016.0,1.000000,0.000000,0.000000,2.0,1.000000,177.0,True,...,False,False,True,False,False,True,False,False,False,-1
102346,40.72826,-73.98422,2017.0,1.000000,2.197225,0.148420,4.0,1.693147,152.0,False,...,False,False,False,True,False,False,False,True,False,-1
102347,40.70862,-73.94651,2003.0,1.000000,0.000000,0.000000,3.0,1.000000,227.0,False,...,False,True,False,False,False,False,False,True,False,-1
102349,40.67505,-73.98045,2009.0,2.098612,0.000000,0.000000,5.0,1.000000,342.0,True,...,False,False,True,False,False,False,False,True,False,-1
102351,40.76807,-73.98342,2010.0,1.000000,0.000000,0.000000,3.0,1.000000,69.0,True,...,False,True,False,False,False,True,False,False,False,-1

## PART B : DBSCAN

### B1. Initial DBSCAN model
1. Fit a DBSCAN model on the scaled data.
1. Start with reasonable values for:
   - eps
   - min_samples
3. Report:
    - Parameter values used
    - Number of clusters found (excluding noise)
    - Number of noise points
    - Your chosen evaluation metric score

In [61]:
from sklearn.cluster import DBSCAN

dbs_eps = 0.5
dbs_min_sam = 5

dbscan = DBSCAN(
    eps = dbs_eps,
    min_samples=dbs_min_sam
).fit(X)

In [65]:
from sklearn.metrics import silhouette_score

data['cluster'] = dbscan.labels_
labels = data['cluster'].to_numpy()
data
data.count(["cluster"] == -1)
data["cluster"].value_counts()
n_clusters = len(set(data['cluster']) - {-1})

n_noise = (labels == -1).sum()
print("Number of noise points:", n_noise)


print(f"Parameter values used: \n\teps = {dbs_eps}\n\tmin_samples = {dbs_min_sam}")
print("Number of clusters found (excluding noise):",n_clusters)
print("Number of noise points:", ) 

shl_score = silhouette_score(X,

Number of noise points: 97170
Parameter values used:
	eps = 0.5
	min_samples = 5
Number of clusters found (excluding noise): 59
Number of noise points:

In [66]:
data["cluster"].value_counts()

cluster
-1     97170
 20        8
 15        7
 21        7
 23        7
 42        7
 0         6
 6         6
 7         6
 9         6
 36        6
 13        6
 45        6
 1         5
 43        5
 2         5
 26        5
 39        5
 38        5
 3         5
 4         5
 40        5
 34        5
 5         5
 58        5
 8         5
 54        5
 57        5
 24        5
 10        5
 11        5
 12        5
 51        5
 14        5
 16        5
 44        5
 17        5
 18        5
 56        5
 19        5
 22        5
 41        5
 55        5
 25        5
 33        5
 52        5
 27        5
 28        5
 29        5
 30        5
 53        5
 31        5
 32        5
 47        5
 35        5
 37        5
 46        5
 50        5
 48        5
 49        5
Name: count, dtype: int64