In [6]:
import pandas as pd
import numpy as np

In [7]:
#Load it and print the shape
airbnb_data = pd.read_csv('data/raw/Airbnb_Open_Data.csv', low_memory=False)
df = airbnb_data

df_shape = df.shape

print(f'Dataframe rows: {df_shape[0]}')
print(f'Dataframe columns: {df_shape[1]}')

print("\n___FIRST 5 ROWS___")
display(df.head())

#print("\n___INFO___")
#df.info

Dataframe rows: 102599
Dataframe columns: 26

___FIRST 5 ROWS___

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [8]:
#Identify numerical, categorical, and missing columns


def get_numerical_cols(data_frame):
    numerical_cols = data_frame.select_dtypes(include=["int64", "float64"]).columns.tolist()
    print(f'NUMERICAL COLUMNS count: {len(numerical_cols)}\n{numerical_cols}')
    return numerical_cols

def get_categorical_cols(data_frame):
    categorical_cols = df.select_dtypes(include=["str" ,"object", "category"]).columns.tolist()
    print(f'\nCATEGORICAL COLUMNS count: {len(categorical_cols)}\n{categorical_cols}')
    return categorical_cols

def get_missing_cols(data_frame):
    missing_count = data_frame.isnull().sum()
    missing_cols = missing_count[missing_count > 0]
    print(f"\nMissing columns: \n-------------------------------------------\n{missing_cols}") if ~missing_cols.empty else print("NO missing columns")
    return missing_cols
    

#numerical_col
num_cols = get_numerical_cols(df)

#categorical columns 
cat_cols = get_categorical_cols(df)

#Missing columns
miss_cols = get_missing_cols(df)

NUMERICAL COLUMNS count: 11
['id', 'host id', 'lat', 'long', 'Construction year', 'minimum nights', 'number of reviews', 'reviews per month', 'review rate number', 'calculated host listings count', 'availability 365']

CATEGORICAL COLUMNS count: 15
['NAME', 'host_identity_verified', 'host name', 'neighbourhood group', 'neighbourhood', 'country', 'country code', 'instant_bookable', 'cancellation_policy', 'room type', 'price', 'service fee', 'last review', 'house_rules', 'license']

Missing columns:
-------------------------------------------
NAME                                 250
host_identity_verified               289
host name                            406
neighbourhood group                   29
neighbourhood                         16
lat                                    8
long                                   8
country                              532
country code                         131
instant_bookable                     105
cancellation_policy                   76
Construction year                    214
price                                247
service fee                          273
minimum nights                       409
number of reviews                    183
last review                        15893
reviews per month                  15879
review rate number                   326
calculated host listings count       319
availability 365                     448
house_rules                        52131
license                           102597
dtype: int64

/tmp/ipykernel_5411/2251129198.py:17: DeprecationWarning: Bitwise inversion '~' on bool is deprecated and will be removed in Python 3.16. This returns the bitwise inversion of the underlying int object and is usually not what you expect from negating a bool. Use the 'not' operator for boolean negation or ~int(x) if you really want the bitwise inversion of the underlying int.
  print(f"\nMissing columns: \n-------------------------------------------\n{missing_cols}") if ~missing_cols.empty else print("NO missing columns")

In [44]:
#Build a full data dictionary with descriptions

data_dict = pd.read_csv("data/raw/Airbnb_Open_Data_Dictionary.csv", delimiter=";",quotechar="'",low_memory=False)

empty_desc_rows = data_dict[data_dict["Description"].isnull()]

empty_desc_rows

                          Field  Type Description
1                   listing_url  text         NaN
15           host_response_time   NaN         NaN
16           host_response_rate   NaN         NaN
19           host_thumbnail_url  text         NaN
20             host_picture_url  text         NaN
21           host_neighbourhood  text         NaN
24           host_verifications   NaN         NaN
27                neighbourhood  text         NaN
39                    amenities  json         NaN
49             calendar_updated  date         NaN
55        calendar_last_scraped  date         NaN
61         review_scores_rating   NaN         NaN
62       review_scores_accuracy   NaN         NaN
63    review_scores_cleanliness   NaN         NaN
64        review_scores_checkin   NaN         NaN
65  review_scores_communication   NaN         NaN
66       review_scores_location   NaN         NaN
67          review_scores_value   NaN         NaN

In [ ]:
manual_desc = {
    "listing_url": "The URL(web) address where the Aribnb listing can be found.",
    "hostname_response_time": "How quickly the host typically responds to messages.",
    "host_response_rate": "The percentage of the messagees the host usually responds to."
    "host_thumbnail_url": "

In [ ]:
data_dict = pd.DataFrame({
    "Column Name": df.columns,
    "Data type" : df.dtypes.astype(str).values,
    "missing values": df.isnull().sum().values,
    "unigue values": df.nunique().values,
})

In [ ]:
#Convert at least two columns to the correct type

In [ ]:
#Extract two meaningful insights